import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Communication Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Route</h1>
      </main>
    </>
  );
};

export default Home;
