import { useSession } from "next-auth/react";
import Head from "next/head";
import Home from "../components/Home";
import UserEntryPage from "../components/Home/UserEntryPage";
const HomePage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Communication Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{session ? <UserEntryPage /> : <Home />}</main>
    </>
  );
};

export default HomePage;
