import { signIn } from "next-auth/react";
import Head from "next/head";
import useFetch from "../../hooks/useFatch";
import { GET_USERS_DATA } from "../../qql-api/user";
import { IUser } from "../../tyeps";

const Home = () => {
  const { data, isLoading, isError } = useFetch<IUser[]>(["noman", 9], GET_USERS_DATA, { limit: 10, offset: 0 });
  return (
    <>
      <Head>
        <title>Communication Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Route</h1>
        {
          // eslint-disable-next-line react/jsx-key
          data?.payload?.map(({ id, name, email, role }, i) => (
            <div key={id} className="flex justify-center items-center gap-y-20">
              <p>Id.: {id}:</p>
              <p className="text-green-300">NAME: {name}</p>
              <p className="text-orange-300">{email}</p>
              <p className="text-blue-500">{role}</p>
              <button className=" text-red-500 px-3 py-2  rounded bg-orange-300">Delete</button>
            </div>
          ))
        }
        <button onClick={() => signIn()}>Sign in</button>
      </main>
    </>
  );
};

export default Home;
